### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ben-eb** [logicalparadox/matcha#20]
Am I missing something?

```
./node_modules/.bin/matcha bench.js 
child_process: customFds option is deprecated, use stdio instead.

                      test
                 wait » function () {
        test(25);
    }/Users/bbriggs/projects/test/node_modules/matcha/lib/matcha/bench.js:122
  var runner = this.fn.length === 0
                      ^
TypeError: Cannot read property 'length' of undefined
    at Bench.runAdaptive (/Users/bbriggs/projects/test/node_modules/matcha/lib/matcha/bench.js:122:23)
    at Bench.run (/Users/bbriggs/projects/test/node_modules/matcha/lib/matcha/bench.js:67:10)
    at /Users/bbriggs/projects/test/node_modules/matcha/lib/matcha/runner.js:125:11
    at iterate (/Users/bbriggs/projects/test/node_modules/matcha/lib/matcha/utils.js:28:5)
    at exports.series (/Users/bbriggs/projects/test/node_modules/matcha/lib/matcha/utils.js:37:3)
    at Runner.runBenches (/Users/bbriggs/projects/test/node_modules/matcha/lib/matcha/runner.js:123:3)
    at iterator (/Users/bbriggs/projects/test/node_modules/matcha/lib/matcha/runner.js:80:5)
    at iterate (/Users/bbriggs/projects/test/node_modules/matcha/lib/matcha/utils.js:28:5)
    at cb (/Users/bbriggs/projects/test/node_modules/matcha/lib/matcha/utils.js:30:26)
    at iterate (/Users/bbriggs/projects/test/node_modules/matcha/lib/matcha/utils.js:27:21)
```

bench.js:

```js
function test (n) {
    return n * 5;
}

suite('test', function () {
    bench(function () {
        test(25);
    });
});
```

node version:

```
node --version
v0.12.2
```

**Comment by phuedx** [comment]
The first argument of `bench` is the name of the benchmark.

```js
function test (n) {
    return n * 5;
}

suite('test', function () {
    bench('25', function () {
        test(25);
    });
});
```

should work just fine.

**Comment by ben-eb** [comment]
@phuedx Thanks. :+1:
